package com.sodogku.libraries.puzzle

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotEquals

/**
 * The key that carries the claim "our boards do not repeat".
 *
 * Tested here on boards small enough to write out and check by eye, rather than
 * only through the shipped pack. A pack of a thousand distinct boards passes
 * `LevelPackVerificationTest` whether the key sees symmetries or not, so a key
 * that quietly stopped rotating would leave that test green and the claim
 * false.
 */
class CanonicalKeyTest {

    @Test
    fun aBoardIsItsOwnKey() {
        val board = Fixtures.uniqueFourByFour()

        assertEquals(board.canonicalKey(), board.canonicalKey())
    }

    @Test
    fun everyTurnAndFlipOfABoardKeysTheSame() {
        // All eight: four quarter turns and each of them mirrored. Generated by
        // transforming the board rather than by listing strings, so this checks
        // the key against the geometry and not against a copy of its own output.
        val board = Fixtures.uniqueFourByFour()
        val key = board.canonicalKey()

        var turned = board
        repeat(4) { turn ->
            assertEquals(key, turned.canonicalKey(), "a board turned $turn quarters keyed differently")
            assertEquals(key, turned.mirrored().canonicalKey(), "turn $turn mirrored keyed differently")
            turned = turned.turned()
        }
    }

    @Test
    fun renamingTheRegionsKeysTheSame() {
        // Regions carry no meaning beyond one dog each, so their ids are a
        // labelling. The same partition with the letters swapped is the same
        // puzzle, and on screen it is the same board in different colors.
        val board = Board.parse(
            "BAAA" +
                "BBCA" +
                "DDCC" +
                "DDDD",
        )
        val recolored = Board.parse(
            "CDDD" +
                "CCAD" +
                "BBAA" +
                "BBBB",
        )

        assertEquals(board.canonicalKey(), recolored.canonicalKey())
    }

    @Test
    fun twoDifferentPartitionsKeyDifferently() {
        // The half that matters in the other direction. A key that collapsed
        // everything would make the pack look flawlessly non-repeating.
        assertNotEquals(
            Fixtures.uniqueFourByFour().canonicalKey(),
            Fixtures.ambiguousFourByFour().canonicalKey(),
        )
    }

    /** A quarter turn clockwise, matching the transform the key sweeps over. */
    private fun Board.turned(): Board = Board(
        size,
        IntArray(size * size) { index ->
            regions[(size - 1 - index % size) * size + index / size]
        },
    )

    private fun Board.mirrored(): Board = Board(
        size,
        IntArray(size * size) { index ->
            regions[index / size * size + (size - 1 - index % size)]
        },
    )
}
