package com.sodogku.libraries.levels

import com.sodogku.libraries.puzzle.Board
import com.sodogku.libraries.puzzle.Solution
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith

/**
 * The one line of text a shipped level is stored as, both directions.
 *
 * Packs are generated by a tool and read by the app, and nobody looks at them
 * in between, so the format is a contract between two programs with no human
 * checking it. The encoded string is therefore pinned literally rather than
 * round-tripped alone: a round trip stays green for a codec that changed its
 * separator on both sides at once, and every committed pack would then fail to
 * load in a build somebody has already installed.
 *
 * The refusals are the rest of the file, and they exist because the fields
 * repeat information. Size is written separately from the region string and
 * from the solution, so a generator bug can leave them disagreeing. Catching
 * that at the boundary turns a confusing out-of-bounds somewhere inside the
 * board into a message naming the line that was wrong.
 *
 * ### Not here
 *
 * Whether a decoded board is solvable, or how hard it is, belongs to
 * `:libraries:puzzle`. Whether the shipped packs actually contain what they
 * claim is the generator's own verification.
 */
class LevelCodecTest {

    private val level = LevelDefinition(
        id = 7,
        board = Board.parse("BAAABBCADDCCDDDD"),
        solution = Solution(intArrayOf(2, 0, 3, 1)),
        difficulty = 2,
    )

    @Test
    fun encode_producesThePipeDelimitedLine() {
        assertEquals("7|4|BAAABBCADDCCDDDD|2031|2", LevelCodec.encode(level))
    }

    @Test
    fun decode_readsItBack() {
        assertEquals(level, LevelCodec.decode("7|4|BAAABBCADDCCDDDD|2031|2"))
    }

    @Test
    fun decode_rejectsAWrongFieldCount() {
        assertFailsWith<IllegalArgumentException> { LevelCodec.decode("7|4|BAAABBCADDCCDDDD|2031") }
    }

    @Test
    fun decode_rejectsRegionsThatDoNotMatchTheDeclaredSize() {
        // The size field and the region string are independently written, so a
        // generator bug could disagree between them. Catch it at the boundary
        // rather than as a confusing out-of-bounds later.
        assertFailsWith<IllegalArgumentException> { LevelCodec.decode("7|4|BAAABB|2031|2") }
    }

    @Test
    fun decode_rejectsASolutionThatDoesNotMatchTheDeclaredSize() {
        assertFailsWith<IllegalArgumentException> {
            LevelCodec.decode("7|4|BAAABBCADDCCDDDD|203|2")
        }
    }

    @Test
    fun decode_rejectsAnUnknownRegionLetter() {
        assertFailsWith<IllegalArgumentException> {
            LevelCodec.decode("7|4|BAAABBCADDCCDDDZ|2031|2")
        }
    }
}
