package com.sodogku.tools.levelgen

import com.sodogku.libraries.levels.CurveBand
import com.sodogku.libraries.levels.LevelCodec
import com.sodogku.libraries.levels.LevelCurve
import com.sodogku.libraries.levels.LevelDefinition
import java.io.File
import kotlin.random.Random
import kotlin.system.exitProcess
import kotlin.time.TimeSource

/**
 * Generates the shipped level packs.
 *
 * ```
 * ./gradlew :tools:level-generator:run
 * ./gradlew :tools:level-generator:run --args="--seed 7"
 * ```
 *
 * Deterministic for a given seed, so regenerating without changing the seed
 * reproduces the pack byte for byte and a diff on the generated source shows a
 * real change rather than churn.
 *
 * Output is Kotlin source, not an asset. Packs then load identically in a unit
 * test, on Android and on iOS with no resource plumbing in the way, and a
 * malformed pack fails the build rather than the app.
 */
fun main(args: Array<String>) {
    val seed = args.optionValue("--seed")?.toIntOrNull() ?: DEFAULT_SEED
    val outputDir = File(args.optionValue("--out") ?: DEFAULT_OUTPUT_DIR)

    println("Generating packs with seed $seed into ${outputDir.path}")
    val started = TimeSource.Monotonic.markNow()

    val campaign = generateCampaign(seed)
    val daily = generateDaily(seed)

    outputDir.mkdirs()
    write(outputDir, "CampaignPackData", "CAMPAIGN_LEVEL_LINES", campaign)
    write(outputDir, "DailyPackData", "DAILY_LEVEL_LINES", daily)

    println("Done in ${started.elapsedNow()}: ${campaign.size} campaign, ${daily.size} daily")
}

private fun generateCampaign(seed: Int): List<LevelDefinition> {
    val generator = Generator(Random(seed))
    val levels = mutableListOf<LevelDefinition>()

    LevelCurve.campaign.forEach { band ->
        val started = TimeSource.Monotonic.markNow()
        val candidates = generator.build(band)
        reportShortfall("campaign", band, candidates)
        orderBand(candidates).forEach { levels += it.toLevel(levels.size + 1) }
        println("  ${band.size}x${band.size}: ${candidates.size} levels in ${started.elapsedNow()}")
    }
    return levels
}

/**
 * Fails the run when a band could not be filled, naming the tier that came up
 * short rather than only the total.
 *
 * Which tier is the whole diagnosis: a band short on tier 4 means the budget is
 * too tight for how rare a contradiction board is at that size, and a band
 * short on tier 2 means the grid has run out of distinct shapes. Those want
 * opposite fixes, and "48/60" says neither.
 */
private fun reportShortfall(pack: String, band: CurveBand, candidates: List<Candidate>) {
    if (candidates.size >= band.count) return

    val found = candidates.groupingBy { it.difficulty }.eachCount()
    val missing = band.runs
        .filter { found.getOrElse(it.tier) { 0 } < it.count }
        .joinToString(", ") { "tier ${it.tier}: ${found.getOrElse(it.tier) { 0 }}/${it.count}" }
    System.err.println(
        "$pack band ${band.size}x${band.size} came up short ($missing). " +
            "Raise the attempt budget, or ask the curve for fewer of that tier at this size.",
    )
    exitProcess(1)
}

/**
 * The daily pool is deliberately not the campaign curve. A daily is a three to
 * five minute habit, not a difficulty ramp, so it draws from a narrow band of
 * mid-sized boards and is shuffled rather than sorted — see `LevelCurve`.
 */
private fun generateDaily(seed: Int): List<LevelDefinition> {
    val generator = Generator(Random(seed + DAILY_SEED_OFFSET))
    val levels = mutableListOf<LevelDefinition>()

    LevelCurve.daily.forEach { band ->
        val started = TimeSource.Monotonic.markNow()
        val candidates = generator.build(band)
        reportShortfall("daily", band, candidates)
        candidates.forEach { levels += it.toLevel(levels.size + 1) }
        println("  daily ${band.size}x${band.size}: ${candidates.size} levels in ${started.elapsedNow()}")
    }
    return levels.shuffled(Random(seed + DAILY_SEED_OFFSET)).mapIndexed { index, level ->
        level.copy(id = index + 1)
    }
}

private fun write(dir: File, className: String, property: String, levels: List<LevelDefinition>) {
    val lines = levels.joinToString(",\n") { "    \"${LevelCodec.encode(it)}\"" }
    val file = File(dir, "$className.kt")
    file.writeText(
        """
        |package com.sodogku.libraries.levels.generated
        |
        |// GENERATED by :tools:level-generator. Do not edit by hand.
        |// Regenerate with: ./gradlew :tools:level-generator:run
        |//
        |// One line per level: id|size|regions|solution|difficulty
        |// Every line is verified unique-solution at generation time and again by
        |// LevelPackVerificationTest on every build.
        |internal val $property: List<String> = listOf(
        |$lines,
        |)
        |
        """.trimMargin(),
    )
    println("  wrote ${file.path} (${levels.size} levels, ${file.length() / 1024}KB)")
}

private fun Array<String>.optionValue(name: String): String? =
    indexOf(name).takeIf { it >= 0 && it + 1 < size }?.let { this[it + 1] }

private const val DEFAULT_SEED = 20260907
private const val DAILY_SEED_OFFSET = 104_729
private const val DEFAULT_OUTPUT_DIR =
    "libraries/levels/src/commonMain/kotlin/com/sodogku/libraries/levels/generated"
