package com.sodogku.tools.levelgen

import com.sodogku.libraries.levels.LevelCodec
import com.sodogku.libraries.levels.LevelDefinition
import java.io.File
import kotlin.random.Random
import kotlin.system.exitProcess
import kotlin.time.TimeSource

/**
 * Generates the shipped level packs.
 *
 * ```
 * ./gradlew :tools:level-generator:run
 * ./gradlew :tools:level-generator:run --args="--seed 7"
 * ```
 *
 * Deterministic for a given seed, so regenerating without changing the seed
 * reproduces the pack byte for byte and a diff on the generated source shows a
 * real change rather than churn.
 *
 * Output is Kotlin source, not an asset. Packs then load identically in a unit
 * test, on Android and on iOS with no resource plumbing in the way, and a
 * malformed pack fails the build rather than the app.
 */
fun main(args: Array<String>) {
    val seed = args.optionValue("--seed")?.toIntOrNull() ?: DEFAULT_SEED
    val outputDir = File(args.optionValue("--out") ?: DEFAULT_OUTPUT_DIR)

    println("Generating packs with seed $seed into ${outputDir.path}")
    val started = TimeSource.Monotonic.markNow()

    val campaign = generateCampaign(seed)
    val daily = generateDaily(seed)

    outputDir.mkdirs()
    write(outputDir, "CampaignPackData", "CAMPAIGN_LEVEL_LINES", campaign)
    write(outputDir, "DailyPackData", "DAILY_LEVEL_LINES", daily)

    println("Done in ${started.elapsedNow()}: ${campaign.size} campaign, ${daily.size} daily")
}

private fun generateCampaign(seed: Int): List<LevelDefinition> {
    val generator = Generator(Random(seed))
    val levels = mutableListOf<LevelDefinition>()

    CAMPAIGN_BANDS.forEach { band ->
        val started = TimeSource.Monotonic.markNow()
        val candidates = generator.build(band.size, band.count, band.maxDifficulty)
        if (candidates.size < band.count) {
            System.err.println(
                "Band ${band.size}x${band.size} came up short: ${candidates.size}/${band.count}. " +
                    "Raise the attempt budget or the refinement budget.",
            )
            exitProcess(1)
        }
        orderBand(candidates).forEach { levels += it.toLevel(levels.size + 1) }
        println("  ${band.size}x${band.size}: ${candidates.size} levels in ${started.elapsedNow()}")
    }
    return levels
}

/**
 * The daily pool is deliberately not the campaign curve. A daily is a three to
 * five minute habit, not a difficulty ramp, so it draws from a narrow band of
 * mid-sized boards and is left in generation order rather than sorted.
 */
private fun generateDaily(seed: Int): List<LevelDefinition> {
    val generator = Generator(Random(seed + DAILY_SEED_OFFSET))
    val levels = mutableListOf<LevelDefinition>()

    DAILY_BANDS.forEach { band ->
        val started = TimeSource.Monotonic.markNow()
        val candidates = generator.build(band.size, band.count, band.maxDifficulty)
        if (candidates.size < band.count) {
            System.err.println(
                "Daily ${band.size}x${band.size} came up short: ${candidates.size}/${band.count}",
            )
            exitProcess(1)
        }
        candidates.forEach { levels += it.toLevel(levels.size + 1) }
        println("  daily ${band.size}x${band.size}: ${candidates.size} levels in ${started.elapsedNow()}")
    }
    return levels.shuffled(Random(seed + DAILY_SEED_OFFSET)).mapIndexed { index, level ->
        level.copy(id = index + 1)
    }
}

private fun write(dir: File, className: String, property: String, levels: List<LevelDefinition>) {
    val lines = levels.joinToString(",\n") { "    \"${LevelCodec.encode(it)}\"" }
    val file = File(dir, "$className.kt")
    file.writeText(
        """
        |package com.sodogku.libraries.levels.generated
        |
        |// GENERATED by :tools:level-generator. Do not edit by hand.
        |// Regenerate with: ./gradlew :tools:level-generator:run
        |//
        |// One line per level: id|size|regions|solution|difficulty
        |// Every line is verified unique-solution at generation time and again by
        |// LevelPackVerificationTest on every build.
        |internal val $property: List<String> = listOf(
        |$lines,
        |)
        |
        """.trimMargin(),
    )
    println("  wrote ${file.path} (${levels.size} levels, ${file.length() / 1024}KB)")
}

private fun Array<String>.optionValue(name: String): String? =
    indexOf(name).takeIf { it >= 0 && it + 1 < size }?.let { this[it + 1] }

/** Grid size bands for the 500-level campaign, per docs/SPEC.md section 1.7. */
private val CAMPAIGN_BANDS = listOf(
    Band(size = 4, count = 10, maxDifficulty = TUTORIAL_MAX_DIFFICULTY),
    Band(size = 5, count = 30, maxDifficulty = EARLY_MAX_DIFFICULTY),
    Band(size = 6, count = 60),
    Band(size = 7, count = 80),
    Band(size = 8, count = 100),
    Band(size = 9, count = 110),
    Band(size = 10, count = 110),
)

/** Two years of dailies, drawn from mid-sized boards only. */
private val DAILY_BANDS = listOf(
    Band(size = 6, count = 240),
    Band(size = 7, count = 250),
    Band(size = 8, count = 240),
)

/** Levels 1 to 10 are the guided tutorial; nothing there may need more than a
 *  single confinement step. */
private const val TUTORIAL_MAX_DIFFICULTY = 2

/** The 5x5 band is still teaching. Sets are fine, contradictions are not. */
private const val EARLY_MAX_DIFFICULTY = 3

private const val DEFAULT_SEED = 20260907
private const val DAILY_SEED_OFFSET = 104_729
private const val DEFAULT_OUTPUT_DIR =
    "libraries/levels/src/commonMain/kotlin/com/sodogku/libraries/levels/generated"
